import type { Product, Order, Customer, Testimonial } from "./types"

// Mock Products
export const mockProducts: Product[] = [
  {
    id: "P001",
    name: "Smart Speaker Pro",
    category: "Loa thông minh",
    categoryId: "smart-speakers",
    price: 1999000,
    originalPrice: 2499000,
    stock: 45,
    status: "In Stock",
    rating: 4.5,
    reviewCount: 128,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Loa thông minh với trợ lý ảo, âm thanh 360 độ và khả năng kết nối đa thiết bị.",
  },
  {
    id: "P002",
    name: "Smart Light Bulb",
    category: "Đèn thông minh",
    categoryId: "smart-lights",
    price: 399000,
    stock: 120,
    status: "In Stock",
    rating: 4.2,
    reviewCount: 95,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Bóng đèn LED thông minh với 16 triệu màu, điều khiển qua ứng dụng và giọng nói.",
  },
  {
    id: "P003",
    name: "Smart Security Camera",
    category: "An ninh",
    categoryId: "security",
    price: 1499000,
    originalPrice: 1799000,
    stock: 18,
    status: "Low Stock",
    rating: 4.7,
    reviewCount: 64,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Camera an ninh thông minh với độ phân giải 2K, tầm nhìn đêm và phát hiện chuyển động.",
  },
  {
    id: "P004",
    name: "Smart Thermostat",
    category: "Điều nhiệt",
    categoryId: "thermostats",
    price: 1299000,
    stock: 0,
    status: "Out of Stock",
    rating: 4.4,
    reviewCount: 42,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Bộ điều nhiệt thông minh giúp tiết kiệm năng lượng và tối ưu hóa nhiệt độ trong nhà.",
  },
  {
    id: "P005",
    name: "Smart Doorbell",
    category: "An ninh",
    categoryId: "security",
    price: 1899000,
    stock: 32,
    status: "In Stock",
    rating: 4.6,
    reviewCount: 78,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Chuông cửa thông minh với camera HD, đàm thoại hai chiều và thông báo chuyển động.",
  },
  {
    id: "P006",
    name: "Smart TV 4K",
    category: "Giải trí",
    categoryId: "entertainment",
    price: 12990000,
    originalPrice: 14990000,
    stock: 15,
    status: "In Stock",
    rating: 4.8,
    reviewCount: 112,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Smart TV 4K với hệ điều hành thông minh, hỗ trợ nhiều ứng dụng giải trí và điều khiển giọng nói.",
  },
  {
    id: "P007",
    name: "Smart Coffee Maker",
    category: "Nhà bếp",
    categoryId: "kitchen",
    price: 2499000,
    stock: 8,
    status: "Low Stock",
    rating: 4.3,
    reviewCount: 37,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Máy pha cà phê thông minh với lịch trình tự động và điều khiển từ xa qua ứng dụng.",
  },
  {
    id: "P008",
    name: "Smart Indoor Camera",
    category: "Camera",
    categoryId: "cameras",
    price: 899000,
    originalPrice: 1099000,
    stock: 25,
    status: "In Stock",
    rating: 4.1,
    reviewCount: 56,
    imageUrl: "/placeholder.svg?height=400&width=400",
    description: "Camera trong nhà thông minh với góc nhìn rộng, theo dõi chuyển động và tích hợp trợ lý ảo.",
  },
]

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    customer: "Nguyen Van A",
    date: "2023-05-15",
    total: 2398000,
    status: "Delivered",
  },
  {
    id: "ORD-002",
    customer: "Tran Thi B",
    date: "2023-05-18",
    total: 1499000,
    status: "Shipped",
  },
  {
    id: "ORD-003",
    customer: "Le Van C",
    date: "2023-05-20",
    total: 3998000,
    status: "Processing",
  },
  {
    id: "ORD-004",
    customer: "Pham Thi D",
    date: "2023-05-22",
    total: 899000,
    status: "Pending",
  },
  {
    id: "ORD-005",
    customer: "Hoang Van E",
    date: "2023-05-23",
    total: 14889000,
    status: "Delivered",
  },
  {
    id: "ORD-006",
    customer: "Nguyen Thi F",
    date: "2023-05-25",
    total: 2499000,
    status: "Cancelled",
  },
  {
    id: "ORD-007",
    customer: "Tran Van G",
    date: "2023-05-26",
    total: 1299000,
    status: "Processing",
  },
  {
    id: "ORD-008",
    customer: "Le Thi H",
    date: "2023-05-28",
    total: 4397000,
    status: "Shipped",
  },
]

// Mock Customers
export const mockCustomers: Customer[] = [
  {
    id: "C001",
    name: "Nguyen Van A",
    email: "nguyenvana@example.com",
    orders: 5,
    totalSpent: 7890000,
    lastOrder: "2023-05-15",
    avatarColor: "bg-blue-500",
  },
  {
    id: "C002",
    name: "Tran Thi B",
    email: "tranthib@example.com",
    orders: 3,
    totalSpent: 4500000,
    lastOrder: "2023-05-18",
    avatarColor: "bg-pink-500",
  },
  {
    id: "C003",
    name: "Le Van C",
    email: "levanc@example.com",
    orders: 8,
    totalSpent: 12500000,
    lastOrder: "2023-05-20",
    avatarColor: "bg-green-500",
  },
  {
    id: "C004",
    name: "Pham Thi D",
    email: "phamthid@example.com",
    orders: 2,
    totalSpent: 2300000,
    lastOrder: "2023-05-22",
    avatarColor: "bg-purple-500",
  },
  {
    id: "C005",
    name: "Hoang Van E",
    email: "hoangvane@example.com",
    orders: 6,
    totalSpent: 18900000,
    lastOrder: "2023-05-23",
    avatarColor: "bg-yellow-500",
  },
  {
    id: "C006",
    name: "Nguyen Thi F",
    email: "nguyenthif@example.com",
    orders: 1,
    totalSpent: 2499000,
    lastOrder: "2023-05-25",
    avatarColor: "bg-indigo-500",
  },
  {
    id: "C007",
    name: "Tran Van G",
    email: "tranvang@example.com",
    orders: 4,
    totalSpent: 6800000,
    lastOrder: "2023-05-26",
    avatarColor: "bg-red-500",
  },
]

// Mock Testimonials
export const mockTestimonials: Testimonial[] = [
  {
    id: "T001",
    name: "Nguyen Van A",
    title: "Kỹ sư phần mềm",
    location: "Hà Nội",
    quote:
      "Tôi đã mua loa thông minh và đèn thông minh từ Yapee. Chất lượng sản phẩm tuyệt vời và dịch vụ khách hàng rất chu đáo. Tôi sẽ tiếp tục mua sắm tại đây!",
    avatarUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "T002",
    name: "Tran Thi B",
    title: "Giáo viên",
    location: "Hồ Chí Minh",
    quote:
      "Camera an ninh của Yapee đã giúp tôi cảm thấy an tâm hơn về ngôi nhà của mình. Chất lượng hình ảnh rõ nét và ứng dụng rất dễ sử dụng.",
    avatarUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "T003",
    name: "Le Van C",
    title: "Kiến trúc sư",
    location: "Đà Nẵng",
    quote:
      "Tôi đã trang bị toàn bộ ngôi nhà với các thiết bị thông minh từ Yapee. Mọi thứ hoạt động liền mạch với nhau và đã thực sự nâng cao chất lượng cuộc sống của tôi.",
    avatarUrl: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "T004",
    name: "Pham Thi D",
    title: "Bác sĩ",
    location: "Cần Thơ",
    quote:
      "Dịch vụ giao hàng nhanh chóng và sản phẩm đúng như mô tả. Tôi đặc biệt hài lòng với bộ điều nhiệt thông minh, nó đã giúp tôi tiết kiệm đáng kể chi phí điện.",
    avatarUrl: "/placeholder.svg?height=200&width=200",
  },
]
